# Generated by Django 5.2.8 on 2025-12-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_billing_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_shipping_address',
        ),
    ]
