"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Choose environment
ENV = os.getenv("DJANGO_ENV", "local")

ENV_FILE = ".env.prod" if ENV == "production" else ".env.local"
load_dotenv(BASE_DIR / ENV_FILE)


def env_bool(key, default=False):
    return str(os.getenv(key, str(default))).lower() in ("true", "1", "yes")


# SECURITY
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise Exception("DJANGO_SECRET_KEY is not set")


DEBUG = env_bool("DJANGO_DEBUG", default=False)


# ALLOWED_HOSTS
raw_hosts = os.getenv("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]


# CORS & CSRF
FRONTEND_URL = os.getenv('FRONTEND_URL')
BACKEND_URL = os.getenv('BACKEND_URL')
INTERNAL_FRONTEND_URL = os.getenv('INTERNAL_FRONTEND_URL', '')
INTERNAL_BACKEND_URL = os.getenv('INTERNAL_BACKEND_URL', '')

CORS_ALLOWED_ORIGINS = [
    url for url in [
        FRONTEND_URL, 
        BACKEND_URL,
        INTERNAL_FRONTEND_URL,
        INTERNAL_BACKEND_URL
    ] if url
]

CSRF_TRUSTED_ORIGINS = [
    url for url in [
        FRONTEND_URL, 
        BACKEND_URL,
        INTERNAL_FRONTEND_URL,
        INTERNAL_BACKEND_URL
    ] if url
]

CORS_ALLOW_CREDENTIALS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # third-party
    "rest_framework",
    'drf_spectacular',
    "corsheaders",
    #
    'apps.usr',
    'apps.eshop',
]

MIDDLEWARE = [
    #
    "corsheaders.middleware.CorsMiddleware",
    #
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# user model
AUTH_USER_MODEL = "usr.User"
# swappable = 'AUTH_USER_MODEL'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        
        ## for postgres database
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv("DATABASE_DB"),
        'USER': os.getenv("DATABASE_USER"),
        'PASSWORD': os.getenv("DATABASE_PASSWORD"),
        'HOST': os.getenv("DATABASE_HOST"),
        'PORT': os.getenv("DATABASE_PORT"),
    }
}
if not DATABASES["default"]["NAME"]:
    raise Exception("Database variables missing")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Caches settings
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-local',
    }
}



# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT= '587'
EMAIL_HOST_USER= 'nkurudavid44@gmail.com'
EMAIL_HOST_PASSWORD= 'bsob stlx euej gkvv'
EMAIL_USE_TLS='True'



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("DJANGO_TIMEZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static",]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JWT_COOKIE_HTTPONLY = env_bool("JWT_COOKIE_HTTPONLY", default=True)
JWT_COOKIE_SECURE = env_bool("JWT_COOKIE_SECURE", not DEBUG)


# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication', 
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'Dany Shop API',
    'DESCRIPTION': (
        "Welcome to the Dany Shop API! "
        "This API allows seamless access to all features of the Dany Shop e-commerce platform. "
        "Developers can manage products, categories, orders, customers, and payments programmatically. "
        "Whether you are building a mobile app, integrating with third-party services, or automating workflows, "
        "the Dany Shop API provides a fast, reliable, and secure interface to interact with our platform."
    ),
    'VERSION': '1.0.0',
    # 'CONTACT': {
    #     'name': 'Dany Shop Support',
    #     'email': 'support@danyshop.com',
    #     'url': 'https://www.danyshop.com/contact'
    # },
    'LICENSE': {
        'name': 'MIT License',
        'url': 'https://opensource.org/licenses/MIT'
    },
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api',
    'COMPONENT_SPLIT_REQUEST': True, 
    'SCHEMA_COERCE_METHOD_NAMES': { 
        'Retrieve': 'Fetch',
        'List': 'ListAll',
        'Create': 'Add',
        'Update': 'Modify',
        'Partial_update': 'Patch',
        'Destroy': 'Delete',
    },
    'SORT_OPERATIONS': False,
    'SORT_SCHEMA_COMPONENTS': True,
    'SERVE_AUTHENTICATION': ['rest_framework.authentication.BasicAuthentication', 'rest_framework.authentication.SessionAuthentication'],
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],
    'ENABLE_FILE_UPLOADS': True,
}