# Generated by Django 5.2.8 on 2025-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='picture',
        ),
        migrations.AddField(
            model_name='productimage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_data',
            field=models.BinaryField(default=b'', verbose_name='Image Data'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
