# Generated by Django 5.2.8 on 2025-12-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Price'),
        ),
    ]
